# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: pypi-release

on:
    release:
        types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
              python-version: "3.x"
        - name: Install tools
          run: |
              python -m pip install --upgrade pip
              python -m pip install --user poetry==1.7.1
              python -m pip install twine
              # python -m pip install setuptools wheel twine

        - name: Build and publish
          run: |
              poetry build
              twine upload dist/*
          env:
              TWINE_USERNAME: ${{ secrets.PYPI_USERS }}
              TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
