name: pypi-deployment

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
  Run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] #, macos-latest
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install poetry
        run: |
            pip install --user poetry==1.7.1

      - name: Export poetry path
        if: ${{runner.os == 'Linux'}}
        run: |
            export PATH="${PATH}:/root/.poetry/bin"
            # export PATH="$HOME/.poetry/bin:$PATH"

      - name: Install dependencies
        run: |
            poetry install
            source `poetry env info --path`/bin/activate

      - name: Generate coverage report
        run: |
            poetry run pytest -vvv --cov=src/serapeum_utils --cov-report=xml

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
