name: Linux
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
  Run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11"]
    env:
      OS: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install poetry
        run: |
            pip install --user poetry==1.2.2
            export PATH="${PATH}:/root/.poetry/bin"

      - name: Install dependencies
        run: |
            poetry install
            source `poetry env info --path`/bin/activate

      - name: Install & Lint with flake8
        run: |
            pip install flake8
            flake8 --max-line-length=120 src/serapeum_utils/*.py tests/*.py

      - name: Generate coverage report
        run: |
            pip install pytest
            pip install pytest-cov
            poetry run pytest -vvv --cov=src/serapeum_utils --cov-report=xml

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
